DB_USERNAME = 'root'
DB_PASSWORD = '123456qrz'
DB_HOST = 'localhost'
DB_PORT = '3306'
DB_NAME = 'pythonbbs'

DB_URI = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8mb4' % (DB_USERNAME,DB_PASSWORD,DB_HOST,DB_PORT,DB_NAME)

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False